AllCops:
  Exclude:
    - node_modules/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
